"""remove old validation columns

Revision ID: c11a7e1e2ab7
Revises: d20d034a7706
Create Date: 2026-09-09 20:12:29.868832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c11a7e1e2ab7'
down_revision: Union[str, Sequence[str], None] = 'd20d034a7706'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'validated_at')
    op.drop_column('submissions', 'validator_id')
    op.drop_column('submissions', 'validation_note')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('validation_note', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('submissions', sa.Column('validator_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('submissions', sa.Column('validated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
